/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("pets").del();
  await knex("pets").insert([
    {
      id: 1,
      user_id: 1,
      type: "cat",
      breed: "cat",
      name: "Whiskers",
      birth_date: "2019-03-12",
      bio: "Whiskers is a playful and affectionate cat. Always ready to chase toys and curl up in your lap. Loves cuddles and will brighten your day!",
    },
    {
      id: 2,
      user_id: 2,
      type: "dog",
      breed: "dog",
      name: "Buddy",
      birth_date: "2018-06-05",
      bio: "Buddy is a friendly and energetic dog. Enjoys long walks and playing fetch. Very loyal and will be your best friend. Always ready for adventures!",
    },
    {
      id: 3,
      user_id: 3,
      type: "cat",
      breed: "cat",
      name: "Mittens",
      birth_date: "2020-01-10",
      bio: "Mittens is a calm and gentle cat. Enjoys lounging in sunbeams and being petted. A purrfect companion for relaxation.",
    },
    {
      id: 4,
      user_id: 4,
      type: "dog",
      breed: "dog",
      name: "Rocky",
      birth_date: "2017-09-18",
      bio: "Rocky is a brave and active dog. Loves outdoor activities and playing fetch. Will keep you entertained and protect you.",
    },
    {
      id: 5,
      user_id: 5,
      type: "cat",
      breed: "cat",
      name: "Oliver",
      birth_date: "2019-05-03",
      bio: "Oliver is a mischievous and curious cat. Always exploring and finding hidden spots to nap. Will bring joy to your home.",
    },
    {
      id: 6,
      user_id: 6,
      type: "dog",
      breed: "dog",
      name: "Luna",
      birth_date: "2018-11-21",
      bio: "Luna is a loving and intelligent dog. Enjoys learning new tricks and going on long walks. Will be your loyal and clever companion.",
    },
    {
      id: 7,
      user_id: 7,
      type: "cat",
      breed: "cat",
      name: "Simba",
      birth_date: "2020-07-15",
      bio: "Simba is a playful and adventurous cat. Always ready for a game of chase or exploring new territories. Will bring excitement to your life.",
    },
    {
      id: 8,
      user_id: 8,
      type: "dog",
      breed: "dog",
      name: "Max",
      birth_date: "2016-12-09",
      bio: "Max is a loyal and gentle dog. Loves being around people and enjoys belly rubs. Will be your faithful and loving companion.",
    },
    {
      id: 9,
      user_id: 9,
      type: "cat",
      breed: "cat",
      name: "Smokey",
      birth_date: "2017-04-25",
      bio: "Smokey is an independent and mysterious cat. Enjoys observing the world from high places and having quiet moments of solitude.",
    },
    {
      id: 10,
      user_id: 10,
      type: "dog",
      breed: "dog",
      name: "Coco",
      birth_date: "2019-08-07",
      bio: "Coco is a friendly and energetic dog. Loves playing fetch and going for runs. Will bring joy and enthusiasm to your daily life.",
    },
    {
      id: 11,
      user_id: 11,
      type: "cat",
      breed: "cat",
      name: "Ginger",
      birth_date: "2018-02-14",
      bio: "Ginger is a sweet and affectionate cat. Enjoys snuggling and receiving gentle strokes. Will be your loving and calming companion.",
    },
    {
      id: 12,
      user_id: 12,
      type: "dog",
      breed: "dog",
      name: "Daisy",
      birth_date: "2020-09-30",
      bio: "Daisy is a playful and cheerful dog. Loves meeting new people and enjoys outdoor adventures. Will bring happiness to your home.",
    },
    {
      id: 13,
      user_id: 13,
      type: "cat",
      breed: "cat",
      name: "Milo",
      birth_date: "2019-06-28",
      bio: "Milo is an energetic and curious cat. Loves chasing toys and exploring every nook and cranny. Will keep you entertained.",
    },
    {
      id: 14,
      user_id: 14,
      type: "dog",
      breed: "dog",
      name: "Bailey",
      birth_date: "2017-11-05",
      bio: "Bailey is a loyal and friendly dog. Enjoys long walks in nature and playing with other dogs. Will be your trusted and joyful companion.",
    },
    {
      id: 15,
      user_id: 15,
      type: "cat",
      breed: "cat",
      name: "Lily",
      birth_date: "2021-02-03",
      bio: "Lily is a gentle and graceful cat. Enjoys sunbathing and having quiet moments of serenity. Will add elegance to your home.",
    },
  ]);
};
