/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("pet_record").del();
  await knex("pet_record").insert([
    {
      id: 1,
      pet_id: 1,
      user_id: 16,
      booking_id: 1,
      rate: 4,
      note: "The pet was well-behaved and showed great energy throughout.",
    },
    {
      id: 2,
      pet_id: 2,
      user_id: 17,
      booking_id: 2,
      rate: 3,
      note: "The pet was friendly but a bit shy. It took some time to warm up.",
    },
    {
      id: 3,
      pet_id: 3,
      user_id: 18,
      booking_id: 3,
      rate: 5,
      note: "An absolute joy to be around! The pet was playful and full of love.",
    },
    {
      id: 4,
      pet_id: 4,
      user_id: 19,
      booking_id: 4,
      rate: 2,
      note: "The pet seemed a bit anxious and timid during the stay.",
    },
    {
      id: 5,
      pet_id: 5,
      user_id: 20,
      booking_id: 5,
      rate: 1,
      note: "Unfortunately, the pet was aggressive and exhibited destructive behavior.",
    },
    {
      id: 6,
      pet_id: 6,
      user_id: 21,
      booking_id: 6,
      rate: 5,
      note: "A well-trained pet that was obedient and brought lots of joy.",
    },
    {
      id: 7,
      pet_id: 7,
      user_id: 22,
      booking_id: 7,
      rate: 4,
      note: "The pet was friendly and energetic, always ready to play.",
    },
    {
      id: 8,
      pet_id: 8,
      user_id: 23,
      booking_id: 8,
      rate: 3,
      note: "The pet was calm and well-mannered, making the stay pleasant.",
    },
    {
      id: 9,
      pet_id: 9,
      user_id: 24,
      booking_id: 9,
      rate: 5,
      note: "A delightful pet with a friendly and affectionate nature.",
    },
    {
      id: 10,
      pet_id: 10,
      user_id: 25,
      booking_id: 10,
      rate: 2,
      note: "Unfortunately, the pet was uncooperative and exhibited disruptive behavior.",
    },
    {
      id: 11,
      pet_id: 11,
      user_id: 26,
      booking_id: 11,
      rate: 4,
      note: "The pet was playful and had a cheerful attitude throughout the stay.",
    },
    {
      id: 12,
      pet_id: 12,
      user_id: 27,
      booking_id: 12,
      rate: 3,
      note: "The pet was curious and explorative, always keeping things interesting.",
    },
    {
      id: 13,
      pet_id: 13,
      user_id: 28,
      booking_id: 13,
      rate: 5,
      note: "A well-behaved pet that was easy to handle and took instructions well.",
    },
    {
      id: 14,
      pet_id: 14,
      user_id: 29,
      booking_id: 14,
      rate: 1,
      note: "Unfortunately, the pet was aggressive and showed signs of discomfort.",
    },
    {
      id: 15,
      pet_id: 15,
      user_id: 30,
      booking_id: 15,
      rate: 2,
      note: "The pet was nervous and kept to itself, requiring gentle reassurance.",
    },
    {
      id: 16,
      pet_id: 1,
      user_id: 31,
      booking_id: 16,
      rate: 5,
      note: "A lively and spirited pet that brought lots of excitement during the stay.",
    },
    {
      id: 17,
      pet_id: 2,
      user_id: 32,
      booking_id: 17,
      rate: 4,
      note: "The pet was friendly and sociable, enjoying the company of others.",
    },
    {
      id: 18,
      pet_id: 3,
      user_id: 33,
      booking_id: 18,
      rate: 3,
      note: "The pet had a calm and relaxed temperament, making for a peaceful stay.",
    },
    {
      id: 19,
      pet_id: 4,
      user_id: 34,
      booking_id: 19,
      rate: 5,
      note: "A truly lovable pet that showered everyone with affection and joy.",
    },
    {
      id: 20,
      pet_id: 5,
      user_id: 35,
      booking_id: 20,
      rate: 2,
      note: "Unfortunately, the pet was disobedient and showed signs of aggression.",
    },
    {
      id: 21,
      pet_id: 6,
      user_id: 36,
      booking_id: 21,
      rate: 4,
      note: "The pet was well-trained and responded positively to commands.",
    },
    {
      id: 22,
      pet_id: 7,
      user_id: 37,
      booking_id: 22,
      rate: 3,
      note: "The pet was a bit reserved but eventually warmed up to the surroundings.",
    },
    {
      id: 23,
      pet_id: 8,
      user_id: 38,
      booking_id: 23,
      rate: 5,
      note: "An absolutely delightful pet with a friendly and playful nature.",
    },
    {
      id: 24,
      pet_id: 9,
      user_id: 39,
      booking_id: 24,
      rate: 1,
      note: "Unfortunately, the pet was difficult to handle and showed aggressive behavior.",
    },
    {
      id: 25,
      pet_id: 10,
      user_id: 40,
      booking_id: 25,
      rate: 2,
      note: "The pet was anxious and required extra attention and care during the stay.",
    },
    {
      id: 26,
      pet_id: 11,
      user_id: 16,
      booking_id: 26,
      rate: 4,
      note: "The pet was energetic and enjoyed participating in various activities.",
    },
    {
      id: 27,
      pet_id: 12,
      user_id: 17,
      booking_id: 27,
      rate: 3,
      note: "The pet was friendly towards everyone and made new friends easily.",
    },
    {
      id: 28,
      pet_id: 13,
      user_id: 18,
      booking_id: 28,
      rate: 5,
      note: "A well-behaved and disciplined pet that made the stay enjoyable.",
    },
    {
      id: 29,
      pet_id: 14,
      user_id: 19,
      booking_id: 29,
      rate: 1,
      note: "Unfortunately, the pet showed signs of aggression and required careful handling.",
    },
    {
      id: 30,
      pet_id: 15,
      user_id: 20,
      booking_id: 30,
      rate: 2,
      note: "The pet was shy and reserved, taking some time to open up to new people.",
    },
    {
      id: 31,
      pet_id: 1,
      user_id: 21,
      booking_id: 31,
      rate: 5,
      note: "An absolute joy to be around! The pet had a loving and affectionate nature.",
    },
    {
      id: 32,
      pet_id: 2,
      user_id: 22,
      booking_id: 32,
      rate: 4,
      note: "The pet was playful and always ready for exciting adventures.",
    },
    {
      id: 33,
      pet_id: 3,
      user_id: 23,
      booking_id: 33,
      rate: 3,
      note: "The pet was calm and well-behaved, making the stay peaceful and pleasant.",
    },
    {
      id: 34,
      pet_id: 4,
      user_id: 24,
      booking_id: 34,
      rate: 5,
      note: "A lovable and affectionate pet that brought smiles to everyone's faces.",
    },
    {
      id: 35,
      pet_id: 5,
      user_id: 25,
      booking_id: 35,
      rate: 2,
      note: "Unfortunately, the pet was disobedient and required extra attention.",
    },
    {
      id: 36,
      pet_id: 6,
      user_id: 26,
      booking_id: 36,
      rate: 4,
      note: "The pet was well-trained and followed instructions with enthusiasm.",
    },
    {
      id: 37,
      pet_id: 7,
      user_id: 27,
      booking_id: 37,
      rate: 3,
      note: "The pet was initially reserved but gradually became more outgoing.",
    },
    {
      id: 38,
      pet_id: 8,
      user_id: 28,
      booking_id: 38,
      rate: 5,
      note: "A delightful and friendly pet that brought joy to everyone's day.",
    },
    {
      id: 39,
      pet_id: 9,
      user_id: 29,
      booking_id: 39,
      rate: 1,
      note: "Unfortunately, the pet displayed aggressive behavior and required careful handling.",
    },
    {
      id: 40,
      pet_id: 10,
      user_id: 30,
      booking_id: 40,
      rate: 2,
      note: "The pet was anxious and needed reassurance and comfort during the stay.",
    },
    {
      id: 41,
      pet_id: 11,
      user_id: 31,
      booking_id: 41,
      rate: 4,
      note: "The pet was energetic and brought a lively spirit to the surroundings.",
    },
    {
      id: 42,
      pet_id: 12,
      user_id: 32,
      booking_id: 42,
      rate: 3,
      note: "The pet was friendly and sociable, always seeking companionship.",
    },
    {
      id: 43,
      pet_id: 13,
      user_id: 33,
      booking_id: 43,
      rate: 5,
      note: "A well-behaved pet that was easy to care for and bonded quickly.",
    },
    {
      id: 44,
      pet_id: 14,
      user_id: 34,
      booking_id: 44,
      rate: 1,
      note: "Unfortunately, the pet displayed aggressive behavior and required extra attention.",
    },
    {
      id: 45,
      pet_id: 15,
      user_id: 35,
      booking_id: 45,
      rate: 2,
      note: "The pet was timid and required a gentle approach to feel comfortable.",
    },
    {
      id: 46,
      pet_id: 1,
      user_id: 36,
      booking_id: 46,
      rate: 5,
      note: "An absolute delight to have around! The pet brought joy and laughter.",
    },
    {
      id: 47,
      pet_id: 2,
      user_id: 37,
      booking_id: 47,
      rate: 4,
      note: "The pet was active and playful, always ready for an adventure.",
    },
    {
      id: 48,
      pet_id: 3,
      user_id: 38,
      booking_id: 48,
      rate: 3,
      note: "The pet had a calm and peaceful nature, making the stay relaxing.",
    },
    {
      id: 49,
      pet_id: 4,
      user_id: 39,
      booking_id: 49,
      rate: 5,
      note: "A loving and affectionate pet that formed strong bonds with everyone.",
    },
    {
      id: 50,
      pet_id: 5,
      user_id: 40,
      booking_id: 50,
      rate: 2,
      note: "Unfortunately, the pet was challenging to handle and required extra attention.",
    },
  ]);
};
